-- Grid: share de conversão por FLAG_TIPO_CANAL (AUTOMATIZADA/EA/MKT/PRODUTOS) e por
-- FLAG_TIPO (formato do canal), mês a mês, pra ver se a composição do mix de conversão mudou
-- depois de abril/2026.
--
-- Base: tabela _AJUSTADA, não a raw. A raw (0_AUT_TBL_CONGRATS_ADQ_MLB_TOTAL) perde uma fração
-- crescente de clientes a partir de março (chegou a -23% em agosto) e tem BU sujo (4 valores:
-- 'mercadopago'/'mercadolibre'/'EA - MP'/'EA - ML'). A _AJUSTADA tem BU limpo (só
-- mercadopago/mercadolibre), PLACEMENT='EA' já normalizado (sem misturar MP/ML) e captura mais
-- gente em todos os meses (não só EA) -- validado contra o numero de referência do Tableau
-- ("Conversões Por Canal de Aquisição").

WITH

proposta_tc AS (
  -- FLAG_TC (FULL/MICRO) da proposta aceita do cliente naquele mes -- casado por
  -- CUS_CUST_ID + mes
  SELECT DISTINCT
    SAFE_CAST(CUS_CUST_ID AS INT64) AS cus_cust_id,
    DATE_TRUNC(CAST(CCARD_PROP_UPDATE_DT AS DATE), MONTH) AS mes_aceite,
    CASE WHEN CCARD_GLOBAL_LIMIT_AMT_LC <= 100 OR CCARD_PRODUCT_ID = 5
         THEN 'MICRO' ELSE 'FULL' END AS FLAG_TC
  FROM `meli-bi-data.WHOWNER.BT_CCARD_PROPOSAL`
  WHERE sit_site_id = 'MLB'
    AND CCARD_PROP_STATUS = 'accepted'
    AND CAST(CCARD_PROP_UPDATE_DT AS DATE) >= '2026-01-01'
),

base0 AS (
  SELECT
    g.CUS_CUST_ID,
    CAST(g.DT_CONGRATS AS STRING FORMAT 'YYYYMM') AS anomes_conv,
    tc.FLAG_TC,
    CASE WHEN g.BU = 'mercadopago' THEN 'MP' WHEN g.BU = 'mercadolibre' THEN 'ML' ELSE 'OUTRO' END AS BU_NORM,
    CASE
      WHEN g.PLACEMENT IN (
        'PUSH_ML_ENCENDIDO_D1', 'WAITLIST_APPROVED_PUSH', 'PUSH_ML_D10', 'WAITLIST_APPROVED_HERMES',
        'EMAIL_MP_ENCENDIDO', 'PUSH_ML_DROPFLUXO', 'BARRIDA_PENDING_ML_MELIMAS', 'PUSH_ML_CHECKOUT',
        'EMAIL_ML_PD_ENCENDIDO', 'PUSH_ML_UPSELL', 'PUSH_FLOWS_ENC_ENG', 'PUSH_FLOWS_ENC_ACT',
        'PUSH_FLOW_NEW_ENG_MELIMAS', 'BARRIDA_PENDING_ML', 'EMAIL_MP_(071124)', 'CREDIT_CARD_PUSHES_FLOWS',
        'WHATSAPP_TESTE_JUNHO_ML', 'EMAIL_ML_ENCENDIDO', 'TESTE_MAIO_WHATSAPP', 'PUSH', 'EMAIL_FULLL',
        'TESTE_PUSH_LIMITE_ML', 'EMAIL_TESTE_JUNHO_ML', 'PUSH_ML_MICRO_D6', 'PUSH_MP_MAON', 'PUSH_MAON_ML',
        'EMAIL_MICRO', 'PUSH_FLOWS_UPSELL_ENG', 'BARRIDA_PENDING_ML_MICRO', 'CARDS_LISTING_RESTYLING_MICRO_TC',
        'CARDS_LISTING_RESTYLING_FULL_TC', 'PUSH_ML_ENCENDIDO_D1_MICRO', 'EMAIL_D1_MICRO', 'SMART'
      )
      THEN 'AUTOMATIZADA'
      WHEN UPPER(g.PLACEMENT) LIKE '%FLOW%' THEN 'AUTOMATIZADA'
      WHEN UPPER(g.PLACEMENT) = 'EA' THEN 'EA'
      WHEN (g.PLACEMENT LIKE '%0%' OR g.PLACEMENT LIKE '%1%' OR g.PLACEMENT LIKE '%3%' OR g.PLACEMENT LIKE '%5%' OR g.PLACEMENT LIKE '%7%') THEN 'MKT'
      ELSE 'PRODUTOS'
    END AS FLAG_TIPO_CANAL_RAW,
    CASE
      WHEN UPPER(g.PLACEMENT) LIKE '%VIP%' OR UPPER(g.PLACEMENT) LIKE '%PDP%' THEN 'VIP+BOTTOM SHEET'
      WHEN UPPER(g.PLACEMENT) LIKE '%MAIL%' THEN 'EMAIL'
      WHEN UPPER(g.PLACEMENT) LIKE '%PUSH%' THEN 'PUSH'
      WHEN UPPER(g.PLACEMENT) LIKE '%HERMES%' THEN 'PUSH'
      WHEN UPPER(g.PLACEMENT) LIKE '%ELD%' THEN 'PUSH'
      WHEN UPPER(g.PLACEMENT) LIKE '%SMART%' THEN 'PUSH'
      WHEN UPPER(g.PLACEMENT) LIKE '%TC_WAITLIST%' THEN 'PUSH'
      WHEN UPPER(g.PLACEMENT) LIKE '%ML_50%' THEN 'PUSH'
      WHEN UPPER(g.PLACEMENT) LIKE '%ML_35%' THEN 'PUSH'
      WHEN UPPER(g.PLACEMENT) LIKE '%ML_70%' THEN 'PUSH'
      WHEN UPPER(g.PLACEMENT) LIKE '%MP_50%' THEN 'PUSH'
      WHEN UPPER(g.PLACEMENT) LIKE '%MP_35%' THEN 'PUSH'
      WHEN UPPER(g.PLACEMENT) LIKE '%35_EN%' THEN 'PUSH'
      WHEN UPPER(g.PLACEMENT) LIKE '%50_EN%' THEN 'PUSH'
      WHEN UPPER(g.PLACEMENT) LIKE '%MP_70%' THEN 'PUSH'
      WHEN UPPER(g.PLACEMENT) LIKE '%BARRIDA%' THEN 'PUSH'
      WHEN UPPER(g.PLACEMENT) LIKE '%XSELL%' THEN 'BANNER XSELL'
      WHEN UPPER(g.PLACEMENT) LIKE '%MAXWELL%' THEN 'MAXWELL'
      WHEN UPPER(g.PLACEMENT) LIKE '%HUB_LOYALTY%' THEN 'HUB LOYALTY'
      WHEN UPPER(g.PLACEMENT) LIKE '%WPP%' THEN 'WHATSAPP'
      WHEN UPPER(g.PLACEMENT) LIKE '%WHATSAPP%' THEN 'WHATSAPP'
      WHEN UPPER(g.PLACEMENT) LIKE '%CONGRAT%' THEN 'CONGRATS'
      WHEN UPPER(g.PLACEMENT) LIKE '%SHEET%' THEN 'VIP+BOTTOM SHEET'
      WHEN UPPER(g.PLACEMENT) LIKE '%CREDIT_NUMERIC%' THEN 'CREDIT SCORE'
      WHEN UPPER(g.PLACEMENT) LIKE '%CREDIT_SCORING%' THEN 'CREDIT SCORE'
      WHEN UPPER(g.PLACEMENT) LIKE '%ONE PAGE%' THEN 'ONE PAGE'
      WHEN UPPER(g.PLACEMENT) LIKE '%MINICARD%' OR UPPER(g.PLACEMENT) LIKE '%BANNER_DASHBOARD%' OR UPPER(g.PLACEMENT) LIKE '%HOME_ANITTA%' THEN 'MINICARD+DASH'
      WHEN UPPER(g.PLACEMENT) LIKE '%ONBOARDING%' THEN 'ONBOARDING MP'
      WHEN UPPER(g.PLACEMENT) LIKE '%CHO%' THEN 'CHECKOUT'
      WHEN UPPER(g.PLACEMENT) LIKE '%NBT%' THEN 'NBT'
      WHEN UPPER(g.PLACEMENT) LIKE '%QA%' THEN 'QA'
      WHEN UPPER(g.PLACEMENT) LIKE '%WEB%' THEN 'WEB'
      WHEN UPPER(g.PLACEMENT) LIKE '%MODAL%' THEN 'MODAL'
      WHEN UPPER(g.PLACEMENT) LIKE '%CARDS_LISTING%' THEN 'MINICARD+DASH'
      WHEN UPPER(g.PLACEMENT) = 'EA' THEN 'EA'
      WHEN g.PLACEMENT IS NULL THEN 'NULO'
      ELSE 'OUTROS'
    END AS FLAG_TIPO
  FROM `meli-bi-data.SBOX_CREDITSTC.0_AUT_TBL_CONGRATS_ADQ_MLB_TOTAL_AJUSTADA` g
  LEFT JOIN proposta_tc tc
    ON tc.cus_cust_id = SAFE_CAST(g.CUS_CUST_ID AS INT64)
   AND tc.mes_aceite = DATE_TRUNC(CAST(g.DT_CONGRATS AS DATE), MONTH)
  WHERE g.DT_CONGRATS >= '2026-01-01'
),

-- se o FLAG_TIPO ja identificou um formato de comunicacao (PUSH/EMAIL/WHATSAPP/MODAL) mas o
-- canal caiu no ELSE 'PRODUTOS' por nao bater em nenhuma regra especifica, corrige pra
-- AUTOMATIZADA -- evita que campanha nova de push/email sem digito no nome vire "PRODUTOS"
base AS (
  SELECT
    * EXCEPT (FLAG_TIPO_CANAL_RAW),
    CASE
      WHEN FLAG_TIPO_CANAL_RAW = 'PRODUTOS' AND FLAG_TIPO IN ('PUSH', 'EMAIL', 'WHATSAPP', 'MODAL')
        THEN 'AUTOMATIZADA'
      ELSE FLAG_TIPO_CANAL_RAW
    END AS FLAG_TIPO_CANAL
  FROM base0
),

agg AS (
  SELECT
    anomes_conv,
    BU_NORM,
    COALESCE(FLAG_TC, 'SEM_TC') AS FLAG_TC,
    FLAG_TIPO_CANAL,
    FLAG_TIPO,
    COUNT(DISTINCT CUS_CUST_ID) AS qtd_conv
  FROM base
  GROUP BY 1, 2, 3, 4, 5
)

SELECT
  anomes_conv,
  BU_NORM,
  FLAG_TC,
  FLAG_TIPO_CANAL,
  FLAG_TIPO,
  qtd_conv
FROM agg
ORDER BY anomes_conv, BU_NORM, FLAG_TC, FLAG_TIPO_CANAL, FLAG_TIPO
